package:
  name: liveprint
  version: "0.1.0"

source:
  git_rev: origin/master
  git_url: https://github.com/monomonedula/liveprint.git

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - opencv

about:
  home: https://github.com/monomonedula/liveprint
  license: Apache License 2.0
  license_file: LICENSE.txt
  summary: Python utility library for dynamic animations projections